name: nimble test
on:
  push:
    branches-ignore:
      - 'feat-*'
    paths:
      - '**/*.nim'
      - './*.nimble'
      - 'tests/**'
      - '.github/workflows/ci.yml'
  pull_request:
  workflow_dispatch:
env:
  nim-version: 'stable'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v4
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ env.nim-version }}
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: test
      run: nimble test

    - name: test js
      run: nimble test -b:js -d:nodejs

    - name: test deno
      run: |
        nim js -o:bin/test-deno.js tests/test1.nim
        deno run --allow-env --allow-read --allow-run bin/test-deno.js
